#!/bin/bash
#SBATCH --job-name=fesom
#SBATCH --partition=gpu
# #SBATCH --reservation=phase2-gpu
#SBATCH --nodes=1
#SBATCH --threads-per-core=2
#SBATCH --time=00:30:00
#SBATCH -o slurm-out.out
#SBATCH -e slurm-err.out
#SBATCH -A ka1298
#SBATCH --mem=0
#SBATCH --exclusive

ulimit -s unlimited
ulimit -c 0

set -x
echo Submitted job: $jobid
squeue -u $USER

# determine JOBID
JOBID=`echo $SLURM_JOB_ID |cut -d"." -f1`

config_folder=../config_pi

ln -s ../bin/fesom.x .           # cp -n ../bin/fesom.x
cp $config_folder/namelist.config  .
cp $config_folder/namelist.forcing .
cp $config_folder/namelist.oce     .
cp $config_folder/namelist.io      .
cp $config_folder/namelist.ice     .
cp $config_folder/namelist.icepack .

export SLURM_DIST_PLANESIZE="8"
export KMP_LIBRARY="turnaround"
export OMPI_MCA_osc="pt2pt"
export UCX_IB_ADDR_TYPE="ib_global"
export OMPI_MCA_coll="^ml"
export OMPI_MCA_coll_hcoll_enable="1"
export HCOLL_MAIN_IB="mlx5_0:1"
export UCX_NET_DEVICES="mlx5_0:1"
export UCX_TLS="mm,cma,dc_mlx5,dc_x,self"
export UCX_UNIFIED_MODE="y"
export HDF5_USE_FILE_LOCKING="FALSE"
export OMPI_MCA_io="romio321"
export MALLOC_TRIM_THRESHOLD_="-1"

# export NVCOMPILER_ACC_NOTIFY=3

date
if [ "$NSYS_PROFILE" = "1" ]
then
    module load nvhpc
    nsys profile -t openacc srun -l fesom.x > "fesom2.0.out"
else
    srun -l --kill-on-bad-exit=1 --nodes=1 --ntasks=2 run_wrapper.sh -n 2 -o 0 -e ../bin/fesom.x > "fesom2.0.out"
fi
date

# qstat -f $PBS_JOBID
#export EXITSTATUS=$?
#if [ ${EXITSTATUS} -eq 0 ] || [ ${EXITSTATUS} -eq 127 ] ; then
#sbatch job_mistral
#fi

